### ISSUE TITLE
OutOfRangeError revisited

### ISSUE THREAD

**Issue by michath** [andreaazzini/segnet#11]
hi,
i experience the same issue, namely -

tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '...' is closed and has insufficient elements (requested 12, current size 0)
File "src/train.py", line 25, in train
`images, labels = inputs(FLAGS.batch, FLAGS.train, FLAGS.train_labels)`
File "src/inputs.py", line 29, in inputs
`shuffle_batch`

but i fail to understand what is meant by "correct resolution" in the related closed issue #10 .
thanks!

**Comment by andreaazzini** [comment]
Hi @michath,
So the problem should be that your images are not 224x224. I understand this is a bummer, and should be fixed, but I do not have the time to add a custom image size feature at the moment. It should actually be very easy, I will do that in a couple of weeks.

However, if you really need it, I encourage you to change every 224 you find in the code, and see if the problems persist. 😊
Email me if you need further information.

**Comment by michath** [comment]
hmmm...
i was sure that since segnet is fully convolutional (with not fully connected layers) there is no need to specify any resolution. in tensorflow that dimension would mean None.
