### ISSUE TITLE
Missing call to self.decode()

### ISSUE THREAD

**Issue by mshunshin** [andreaazzini/segnet#5]
In the latest commit (with the addition of --strided) the call to self.decode() went missing in the refactor.

BW

M

**Comment by andreaazzini** [comment]
Definitely true, the idea was actually to remove the `self.decode()` method and leave `self.inference_with_pooling()` and `self.strided_inference()` only. Do you want to provide a PR as a contribution, or should I fix this? 😊

**Comment by andreaazzini** [comment]
Fixed
